### PR TITLE
Use arrow-cpp's run_export

### LINKED ISSUE #15: Using arrow-cpp run_export
It appears that the `run` dependency for `arrow-cpp` in `omniscidb-cpu` [doesn't use]( https://github.com/conda-forge/omniscidb-cpu-feedstock/blob/85d93553ad5b812231896f67508e8326a501f904/recipe/meta.yaml#L51 ) the new [`run_export` of `arrow-cpp`]( https://github.com/conda-forge/arrow-cpp-feedstock/blob/074a4219fbf43f4f70448c1a5a4cd0cd515e939a/recipe/meta.yaml#L17-L18 ). Would be good to update this to rely on the `run_export`.

### PR DESCRIPTION
**Pull request by jakirkham**
Makes sure we use `arrow-cpp`'s `run_export` to determine the version of `arrow-cpp` we use at runtime.

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes https://github.com/conda-forge/omniscidb-cpu-feedstock/issues/15

xref: https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/321#issuecomment-550536461

### CODE REVIEW

**Comment by jakirkham** [comment]
There is also `arrow-cpp >=0.13.0` in `host` that we probably should drop. Thoughts?

**Comment by xhochy** [comment]
We should remove the version from host and let conda-forge-pinning handle it.

**Comment by xmnlab** [comment]
LGTM. @pearu do you have any thoughts about this PR?

**Comment by jakirkham** [comment]
> We should remove the version from host and let conda-forge-pinning handle it.

Sounds good. Done 😄

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

@jakirkham `arrow-cpp` should appear in the pinnings file.

**Review by pearu — APPROVED** [review]
LGTM, thanks @jakirkham !

**Comment by pearu** [comment]
Is there a way to restart the failing osx check?

**Comment by jakirkham** [comment]
Yeah I've done that manually.

**Comment by jakirkham** [comment]
> @jakirkham `arrow-cpp` should appear in the pinnings file.

We could add it back to `run`. Though that might cause issues since we are [pinnined to `0.15.0` globally]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/50052c574f907a0c903f18fcb3d1bcf507ac30d4/recipe/conda_build_config.yaml#L350-L351 ) and that version didn't have the `run_export`. How do you think we should handle this? My hope is to get through these PRs and then bump to `0.15.1`. Though would be open to other ideas 🙂

**Comment by xhochy** [comment]
@jakirkham I would suspect that a rerender adds `arrow-cpp` to the pinnings file. Thus I called `@conda-forge-admin please rerender`

**Comment by xhochy** [comment]
Otherwise feel free to merge an start the new pinning migration.

**Comment by jakirkham** [comment]
I’ll give it a go local.

**Comment by jakirkham** [comment]
@xhochy, have pushed this in the latest commit 🙂

**Comment by jakirkham** [comment]
It looks like this pinning is resulting in an unresolvable state. How do you feel about overriding the pinning here to use `arrow-cpp` version `0.15.1`?

```
Package zstd conflicts for:
libarchive=3.3 -> zstd[version='>=1.3.3,<1.3.4.0a0|>=1.3.7,<1.3.8.0a0|>=1.4.0,<1.4.1.0a0']
arrow-cpp=0.15.0 -> zstd[version='>=1.4.0,<1.4.1.0a0|>=1.4.3,<1.4.4.0a0']
libgdal[version='>=2.3.*,<3'] -> libtiff[version='>=4.0.10,<5.0a0'] -> zstd[version='>=1.3.3,<1.3.4.0a0|>=1.3.7,<1.3.8.0a0|>=1.4.0,<1.4.1.0a0|>=1.4.3,<1.4.4.0a0']
blosc -> zstd[version='>=1.3.7,<1.3.8.0a0']
```

ref: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=91414&view=logs&jobId=1bf226d3-0e2f-52d8-fa93-7d9e633347b3

**Comment by xhochy** [comment]
`blosc -> zstd[version='>=1.3.7,<1.3.8.0a0']` is a confusing line as `blosc` has no dependencies: https://github.com/conda-forge/blosc-feedstock/blob/eb457e12ea87803f4d70dc29975d9c428ff174c9/recipe/meta.yaml#L22

The actual problem here is that all newer `arrow-cpp` versions are built against `boost-cpp=1.70`. So we cannot upgrade `arrow-cpp` here unless we either update `boost-cpp` here or build `arrow-cpp` against multiple boost versions.

**Comment by pearu** [comment]
Unfortunately, omniscidb 4.8 build will fail with newer boost-cpp versions.

**Comment by pearu** [comment]
However, the next release (not available yet) seems to support newer boost versions (not tested).

**Comment by jakirkham** [comment]
In that case, I'm going to close this out. There doesn't seem to be a clear path forward without a new release. Hopefully you, @pearu, will be able to tackle this in the next release?

**Comment by pearu** [comment]
I can now confirm that the unreleased omniscidb builds ok with boost-cpp 1.70.
@jakirkham , sure, I'll tackle this.
IIUC, the aim is to specify `arrow-cpp` and `boost-cpp` without version restrictions (I haven't look into what `run_export` does, yet)

**Comment by jakirkham** [comment]
Basically `run_export` says if you link against a dependency in `host`, it will be automatically added to `run` with a version constraint determined by that package.

**Pull request closed without merging**
