### PR TITLE
Use gcc compiler for Linux, clean up

### PR DESCRIPTION
**Pull request by pearu**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pearu** [comment]
@conda-forge-admin, please rerender

**Comment by pearu** [comment]
@conda-forge-admin, please rerender

**Comment by pearu** [comment]
@conda-forge/core , re-rendering has some issues, please advice.

**Comment by scopatz** [comment]
What do you mean by some issues?

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
@pearu, there was an issue with the webservice and has been restarted now.

**Comment by pearu** [comment]
@scopatz , I meant conda-forge-linter gave a message `I tried to re-render for you but ran into some issues, please ping conda-forge/core for further assistance.`
@isuruf , thanks for the solution.

**Comment by pearu** [comment]
@conda-forge-admin, please rerender

**Comment by pearu** [comment]
@conda-forge-admin, please rerender

**Comment by pearu** [comment]
@conda-forge-admin, please rerender

**Comment by pearu** [comment]
@xmnlab please review

**Comment by xmnlab** [comment]
LGTM! Thanks @pearu !

**Pull request merged**
